define({
    title: "á_Map Title_Ó",
    format: "á_Format_Ó",
    layout: "á_Layout_Ó",
    settings: "á_Advanced_Ó",
    mapScaleExtent: "á_Map scale/extent_Ó",
    preserve: "á_Preserve_Ó",
    mapScale: "á_map scale_Ó",
    mapExtent: "á_map extent_Ó",
    forceScale: "á_Force scale_Ó",
    getCurrentScale: "á_current_Ó",
    mapMetadata: "á_Layout metadata_Ó",
    author: "á_Author_Ó",
    copyright: "á_Copyright_Ó",
    fullLayoutOptions: "á_Full layout options_Ó",
    scaleBarUnitsMetric: "á_Scale bar units metric_Ó",
    scaleBarUnitsNonMetric: "á_Scale bar units non-metric_Ó",
    unitsMiles: "á_Miles_Ó",
    unitsKilometers: "á_Kilometers_Ó",
    unitsMeters: "á_Meters_Ó",
    unitsFeet: "á_Feet_Ó",
    unitsYards: "á_Yards_Ó",
    unitsNauticalMiles: "á_Nautical Miles_Ó",
    lncludeLegend: "á_Include legend_Ó",
    printQualityOptions: "á_Print quality_Ó",
    dpi: "á_DPI_Ó",
    mapOnlyOptions: "á_MAP_ONLY size_Ó",
    width: "á_Width (px)_Ó",
    height: "á_Height (px)_Ó",
    print: "á_Print_Ó",
    clearList: "á_Clear Prints_Ó",
    creatingPrint: "á_Creating Print_Ó",
    printError: "á_Error, try again_Ó"
});