define({
    title: "Ĳ_Map Title_ä",
    format: "Ĳ_Format_ä",
    layout: "Ĳ_Layout_ä",
    settings: "Ĳ_Advanced_ä",
    mapScaleExtent: "Ĳ_Map scale/extent_ä",
    preserve: "Ĳ_Preserve_ä",
    mapScale: "Ĳ_map scale_ä",
    mapExtent: "Ĳ_map extent_ä",
    forceScale: "Ĳ_Force scale_ä",
    getCurrentScale: "Ĳ_current_ä",
    mapMetadata: "Ĳ_Layout metadata_ä",
    author: "Ĳ_Author_ä",
    copyright: "Ĳ_Copyright_ä",
    fullLayoutOptions: "Ĳ_Full layout options_ä",
    scaleBarUnitsMetric: "Ĳ_Scale bar units metric_ä",
    scaleBarUnitsNonMetric: "Ĳ_Scale bar units non-metric_ä",
    unitsMiles: "Ĳ_Miles_ä",
    unitsKilometers: "Ĳ_Kilometers_ä",
    unitsMeters: "Ĳ_Meters_ä",
    unitsFeet: "Ĳ_Feet_ä",
    unitsYards: "Ĳ_Yards_ä",
    unitsNauticalMiles: "Ĳ_Nautical Miles_ä",
    lncludeLegend: "Ĳ_Include legend_ä",
    printQualityOptions: "Ĳ_Print quality_ä",
    dpi: "Ĳ_DPI_ä",
    mapOnlyOptions: "Ĳ_MAP_ONLY size_ä",
    width: "Ĳ_Width (px)_ä",
    height: "Ĳ_Height (px)_ä",
    print: "Ĳ_Print_ä",
    clearList: "Ĳ_Clear Prints_ä",
    creatingPrint: "Ĳ_Creating Print_ä",
    printError: "Ĳ_Error, try again_ä"
});