define({
    title: "Å_Map Title_ö",
    format: "Å_Format_ö",
    layout: "Å_Layout_ö",
    settings: "Å_Advanced_ö",
    mapScaleExtent: "Å_Map scale/extent_ö",
    preserve: "Å_Preserve_ö",
    mapScale: "Å_map scale_ö",
    mapExtent: "Å_map extent_ö",
    forceScale: "Å_Force scale_ö",
    getCurrentScale: "Å_current_ö",
    mapMetadata: "Å_Layout metadata_ö",
    author: "Å_Author_ö",
    copyright: "Å_Copyright_ö",
    fullLayoutOptions: "Å_Full layout options_ö",
    scaleBarUnitsMetric: "Å_Scale bar units metric_ö",
    scaleBarUnitsNonMetric: "Å_Scale bar units non-metric_ö",
    unitsMiles: "Å_Miles_ö",
    unitsKilometers: "Å_Kilometers_ö",
    unitsMeters: "Å_Meters_ö",
    unitsFeet: "Å_Feet_ö",
    unitsYards: "Å_Yards_ö",
    unitsNauticalMiles: "Å_Nautical Miles_ö",
    lncludeLegend: "Å_Include legend_ö",
    printQualityOptions: "Å_Print quality_ö",
    dpi: "Å_DPI_ö",
    mapOnlyOptions: "Å_MAP_ONLY size_ö",
    width: "Å_Width (px)_ö",
    height: "Å_Height (px)_ö",
    print: "Å_Print_ö",
    clearList: "Å_Clear Prints_ö",
    creatingPrint: "Å_Creating Print_ö",
    printError: "Å_Error, try again_ö"
});