define({
    title: "Į_Map Title_š",
    format: "Į_Format_š",
    layout: "Į_Layout_š",
    settings: "Į_Advanced_š",
    mapScaleExtent: "Į_Map scale/extent_š",
    preserve: "Į_Preserve_š",
    mapScale: "Į_map scale_š",
    mapExtent: "Į_map extent_š",
    forceScale: "Į_Force scale_š",
    getCurrentScale: "Į_current_š",
    mapMetadata: "Į_Layout metadata_š",
    author: "Į_Author_š",
    copyright: "Į_Copyright_š",
    fullLayoutOptions: "Į_Full layout options_š",
    scaleBarUnitsMetric: "Į_Scale bar units metric_š",
    scaleBarUnitsNonMetric: "Į_Scale bar units non-metric_š",
    unitsMiles: "Į_Miles_š",
    unitsKilometers: "Į_Kilometers_š",
    unitsMeters: "Į_Meters_š",
    unitsFeet: "Į_Feet_š",
    unitsYards: "Į_Yards_š",
    unitsNauticalMiles: "Į_Nautical Miles_š",
    lncludeLegend: "Į_Include legend_š",
    printQualityOptions: "Į_Print quality_š",
    dpi: "Į_DPI_š",
    mapOnlyOptions: "Į_MAP_ONLY size_š",
    width: "Į_Width (px)_š",
    height: "Į_Height (px)_š",
    print: "Į_Print_š",
    clearList: "Į_Clear Prints_š",
    creatingPrint: "Į_Creating Print_š",
    printError: "Į_Error, try again_š"
});