define({
    title: "한_Map Title_빠",
    format: "한_Format_빠",
    layout: "한_Layout_빠",
    settings: "한_Advanced_빠",
    mapScaleExtent: "한_Map scale/extent_빠",
    preserve: "한_Preserve_빠",
    mapScale: "한_map scale_빠",
    mapExtent: "한_map extent_빠",
    forceScale: "한_Force scale_빠",
    getCurrentScale: "한_current_빠",
    mapMetadata: "한_Layout metadata_빠",
    author: "한_Author_빠",
    copyright: "한_Copyright_빠",
    fullLayoutOptions: "한_Full layout options_빠",
    scaleBarUnitsMetric: "한_Scale bar units metric_빠",
    scaleBarUnitsNonMetric: "한_Scale bar units non-metric_빠",
    unitsMiles: "한_Miles_빠",
    unitsKilometers: "한_Kilometers_빠",
    unitsMeters: "한_Meters_빠",
    unitsFeet: "한_Feet_빠",
    unitsYards: "한_Yards_빠",
    unitsNauticalMiles: "한_Nautical Miles_빠",
    lncludeLegend: "한_Include legend_빠",
    printQualityOptions: "한_Print quality_빠",
    dpi: "한_DPI_빠",
    mapOnlyOptions: "한_MAP_ONLY size_빠",
    width: "한_Width (px)_빠",
    height: "한_Height (px)_빠",
    print: "한_Print_빠",
    clearList: "한_Clear Prints_빠",
    creatingPrint: "한_Creating Print_빠",
    printError: "한_Error, try again_빠"
});