define({
    title: "ä_Map Title_Ü",
    format: "ä_Format_Ü",
    layout: "ä_Layout_Ü",
    settings: "ä_Advanced_Ü",
    mapScaleExtent: "ä_Map scale/extent_Ü",
    preserve: "ä_Preserve_Ü",
    mapScale: "ä_map scale_Ü",
    mapExtent: "ä_map extent_Ü",
    forceScale: "ä_Force scale_Ü",
    getCurrentScale: "ä_current_Ü",
    mapMetadata: "ä_Layout metadata_Ü",
    author: "ä_Author_Ü",
    copyright: "ä_Copyright_Ü",
    fullLayoutOptions: "ä_Full layout options_Ü",
    scaleBarUnitsMetric: "ä_Scale bar units metric_Ü",
    scaleBarUnitsNonMetric: "ä_Scale bar units non-metric_Ü",
    unitsMiles: "ä_Miles_Ü",
    unitsKilometers: "ä_Kilometers_Ü",
    unitsMeters: "ä_Meters_Ü",
    unitsFeet: "ä_Feet_Ü",
    unitsYards: "ä_Yards_Ü",
    unitsNauticalMiles: "ä_Nautical Miles_Ü",
    lncludeLegend: "ä_Include legend_Ü",
    printQualityOptions: "ä_Print quality_Ü",
    dpi: "ä_DPI_Ü",
    mapOnlyOptions: "ä_MAP_ONLY size_Ü",
    width: "ä_Width (px)_Ü",
    height: "ä_Height (px)_Ü",
    print: "ä_Print_Ü",
    clearList: "ä_Clear Prints_Ü",
    creatingPrint: "ä_Creating Print_Ü",
    printError: "ä_Error, try again_Ü"
});