define({
    title: "ã_Map Title_Ç",
    format: "ã_Format_Ç",
    layout: "ã_Layout_Ç",
    settings: "ã_Advanced_Ç",
    mapScaleExtent: "ã_Map scale/extent_Ç",
    preserve: "ã_Preserve_Ç",
    mapScale: "ã_map scale_Ç",
    mapExtent: "ã_map extent_Ç",
    forceScale: "ã_Force scale_Ç",
    getCurrentScale: "ã_current_Ç",
    mapMetadata: "ã_Layout metadata_Ç",
    author: "ã_Author_Ç",
    copyright: "ã_Copyright_Ç",
    fullLayoutOptions: "ã_Full layout options_Ç",
    scaleBarUnitsMetric: "ã_Scale bar units metric_Ç",
    scaleBarUnitsNonMetric: "ã_Scale bar units non-metric_Ç",
    unitsMiles: "ã_Miles_Ç",
    unitsKilometers: "ã_Kilometers_Ç",
    unitsMeters: "ã_Meters_Ç",
    unitsFeet: "ã_Feet_Ç",
    unitsYards: "ã_Yards_Ç",
    unitsNauticalMiles: "ã_Nautical Miles_Ç",
    lncludeLegend: "ã_Include legend_Ç",
    printQualityOptions: "ã_Print quality_Ç",
    dpi: "ã_DPI_Ç",
    mapOnlyOptions: "ã_MAP_ONLY size_Ç",
    width: "ã_Width (px)_Ç",
    height: "ã_Height (px)_Ç",
    print: "ã_Print_Ç",
    clearList: "ã_Clear Prints_Ç",
    creatingPrint: "ã_Creating Print_Ç",
    printError: "ã_Error, try again_Ç"
});