define({
    title: "Ř_Map Title_ů",
    format: "Ř_Format_ů",
    layout: "Ř_Layout_ů",
    settings: "Ř_Advanced_ů",
    mapScaleExtent: "Ř_Map scale/extent_ů",
    preserve: "Ř_Preserve_ů",
    mapScale: "Ř_map scale_ů",
    mapExtent: "Ř_map extent_ů",
    forceScale: "Ř_Force scale_ů",
    getCurrentScale: "Ř_current_ů",
    mapMetadata: "Ř_Layout metadata_ů",
    author: "Ř_Author_ů",
    copyright: "Ř_Copyright_ů",
    fullLayoutOptions: "Ř_Full layout options_ů",
    scaleBarUnitsMetric: "Ř_Scale bar units metric_ů",
    scaleBarUnitsNonMetric: "Ř_Scale bar units non-metric_ů",
    unitsMiles: "Ř_Miles_ů",
    unitsKilometers: "Ř_Kilometers_ů",
    unitsMeters: "Ř_Meters_ů",
    unitsFeet: "Ř_Feet_ů",
    unitsYards: "Ř_Yards_ů",
    unitsNauticalMiles: "Ř_Nautical Miles_ů",
    lncludeLegend: "Ř_Include legend_ů",
    printQualityOptions: "Ř_Print quality_ů",
    dpi: "Ř_DPI_ů",
    mapOnlyOptions: "Ř_MAP_ONLY size_ů",
    width: "Ř_Width (px)_ů",
    height: "Ř_Height (px)_ů",
    print: "Ř_Print_ů",
    clearList: "Ř_Clear Prints_ů",
    creatingPrint: "Ř_Creating Print_ů",
    printError: "Ř_Error, try again_ů"
});