define({
    title: "ø_Map Title_å",
    format: "ø_Format_å",
    layout: "ø_Layout_å",
    settings: "ø_Advanced_å",
    mapScaleExtent: "ø_Map scale/extent_å",
    preserve: "ø_Preserve_å",
    mapScale: "ø_map scale_å",
    mapExtent: "ø_map extent_å",
    forceScale: "ø_Force scale_å",
    getCurrentScale: "ø_current_å",
    mapMetadata: "ø_Layout metadata_å",
    author: "ø_Author_å",
    copyright: "ø_Copyright_å",
    fullLayoutOptions: "ø_Full layout options_å",
    scaleBarUnitsMetric: "ø_Scale bar units metric_å",
    scaleBarUnitsNonMetric: "ø_Scale bar units non-metric_å",
    unitsMiles: "ø_Miles_å",
    unitsKilometers: "ø_Kilometers_å",
    unitsMeters: "ø_Meters_å",
    unitsFeet: "ø_Feet_å",
    unitsYards: "ø_Yards_å",
    unitsNauticalMiles: "ø_Nautical Miles_å",
    lncludeLegend: "ø_Include legend_å",
    printQualityOptions: "ø_Print quality_å",
    dpi: "ø_DPI_å",
    mapOnlyOptions: "ø_MAP_ONLY size_å",
    width: "ø_Width (px)_å",
    height: "ø_Height (px)_å",
    print: "ø_Print_å",
    clearList: "ø_Clear Prints_å",
    creatingPrint: "ø_Creating Print_å",
    printError: "ø_Error, try again_å"
});