define({
    title: "بيت_Map Title_لاحقة",
    format: "بيت_Format_لاحقة",
    layout: "بيت_Layout_لاحقة",
    settings: "بيت_Advanced_لاحقة",
    mapScaleExtent: "بيت_Map scale/extent_لاحقة",
    preserve: "بيت_Preserve_لاحقة",
    mapScale: "بيت_map scale_لاحقة",
    mapExtent: "بيت_map extent_لاحقة",
    forceScale: "بيت_Force scale_لاحقة",
    getCurrentScale: "بيت_current_لاحقة",
    mapMetadata: "بيت_Layout metadata_لاحقة",
    author: "بيت_Author_لاحقة",
    copyright: "بيت_Copyright_لاحقة",
    fullLayoutOptions: "بيت_Full layout options_لاحقة",
    scaleBarUnitsMetric: "بيت_Scale bar units metric_لاحقة",
    scaleBarUnitsNonMetric: "بيت_Scale bar units non-metric_لاحقة",
    unitsMiles: "بيت_Miles_لاحقة",
    unitsKilometers: "بيت_Kilometers_لاحقة",
    unitsMeters: "بيت_Meters_لاحقة",
    unitsFeet: "بيت_Feet_لاحقة",
    unitsYards: "بيت_Yards_لاحقة",
    unitsNauticalMiles: "بيت_Nautical Miles_لاحقة",
    lncludeLegend: "بيت_Include legend_لاحقة",
    printQualityOptions: "بيت_Print quality_لاحقة",
    dpi: "بيت_DPI_لاحقة",
    mapOnlyOptions: "بيت_MAP_ONLY size_لاحقة",
    width: "بيت_Width (px)_لاحقة",
    height: "بيت_Height (px)_لاحقة",
    print: "بيت_Print_لاحقة",
    clearList: "بيت_Clear Prints_لاحقة",
    creatingPrint: "بيت_Creating Print_لاحقة",
    printError: "بيت_Error, try again_لاحقة"
});