define({
    title: "ķ_Map Title_ū",
    format: "ķ_Format_ū",
    layout: "ķ_Layout_ū",
    settings: "ķ_Advanced_ū",
    mapScaleExtent: "ķ_Map scale/extent_ū",
    preserve: "ķ_Preserve_ū",
    mapScale: "ķ_map scale_ū",
    mapExtent: "ķ_map extent_ū",
    forceScale: "ķ_Force scale_ū",
    getCurrentScale: "ķ_current_ū",
    mapMetadata: "ķ_Layout metadata_ū",
    author: "ķ_Author_ū",
    copyright: "ķ_Copyright_ū",
    fullLayoutOptions: "ķ_Full layout options_ū",
    scaleBarUnitsMetric: "ķ_Scale bar units metric_ū",
    scaleBarUnitsNonMetric: "ķ_Scale bar units non-metric_ū",
    unitsMiles: "ķ_Miles_ū",
    unitsKilometers: "ķ_Kilometers_ū",
    unitsMeters: "ķ_Meters_ū",
    unitsFeet: "ķ_Feet_ū",
    unitsYards: "ķ_Yards_ū",
    unitsNauticalMiles: "ķ_Nautical Miles_ū",
    lncludeLegend: "ķ_Include legend_ū",
    printQualityOptions: "ķ_Print quality_ū",
    dpi: "ķ_DPI_ū",
    mapOnlyOptions: "ķ_MAP_ONLY size_ū",
    width: "ķ_Width (px)_ū",
    height: "ķ_Height (px)_ū",
    print: "ķ_Print_ū",
    clearList: "ķ_Clear Prints_ū",
    creatingPrint: "ķ_Creating Print_ū",
    printError: "ķ_Error, try again_ū"
});