define({
    title: "ı_Map Title_İ",
    format: "ı_Format_İ",
    layout: "ı_Layout_İ",
    settings: "ı_Advanced_İ",
    mapScaleExtent: "ı_Map scale/extent_İ",
    preserve: "ı_Preserve_İ",
    mapScale: "ı_map scale_İ",
    mapExtent: "ı_map extent_İ",
    forceScale: "ı_Force scale_İ",
    getCurrentScale: "ı_current_İ",
    mapMetadata: "ı_Layout metadata_İ",
    author: "ı_Author_İ",
    copyright: "ı_Copyright_İ",
    fullLayoutOptions: "ı_Full layout options_İ",
    scaleBarUnitsMetric: "ı_Scale bar units metric_İ",
    scaleBarUnitsNonMetric: "ı_Scale bar units non-metric_İ",
    unitsMiles: "ı_Miles_İ",
    unitsKilometers: "ı_Kilometers_İ",
    unitsMeters: "ı_Meters_İ",
    unitsFeet: "ı_Feet_İ",
    unitsYards: "ı_Yards_İ",
    unitsNauticalMiles: "ı_Nautical Miles_İ",
    lncludeLegend: "ı_Include legend_İ",
    printQualityOptions: "ı_Print quality_İ",
    dpi: "ı_DPI_İ",
    mapOnlyOptions: "ı_MAP_ONLY size_İ",
    width: "ı_Width (px)_İ",
    height: "ı_Height (px)_İ",
    print: "ı_Print_İ",
    clearList: "ı_Clear Prints_İ",
    creatingPrint: "ı_Creating Print_İ",
    printError: "ı_Error, try again_İ"
});