define({
    title: "ł_Map Title_ą",
    format: "ł_Format_ą",
    layout: "ł_Layout_ą",
    settings: "ł_Advanced_ą",
    mapScaleExtent: "ł_Map scale/extent_ą",
    preserve: "ł_Preserve_ą",
    mapScale: "ł_map scale_ą",
    mapExtent: "ł_map extent_ą",
    forceScale: "ł_Force scale_ą",
    getCurrentScale: "ł_current_ą",
    mapMetadata: "ł_Layout metadata_ą",
    author: "ł_Author_ą",
    copyright: "ł_Copyright_ą",
    fullLayoutOptions: "ł_Full layout options_ą",
    scaleBarUnitsMetric: "ł_Scale bar units metric_ą",
    scaleBarUnitsNonMetric: "ł_Scale bar units non-metric_ą",
    unitsMiles: "ł_Miles_ą",
    unitsKilometers: "ł_Kilometers_ą",
    unitsMeters: "ł_Meters_ą",
    unitsFeet: "ł_Feet_ą",
    unitsYards: "ł_Yards_ą",
    unitsNauticalMiles: "ł_Nautical Miles_ą",
    lncludeLegend: "ł_Include legend_ą",
    printQualityOptions: "ł_Print quality_ą",
    dpi: "ł_DPI_ą",
    mapOnlyOptions: "ł_MAP_ONLY size_ą",
    width: "ł_Width (px)_ą",
    height: "ł_Height (px)_ą",
    print: "ł_Print_ą",
    clearList: "ł_Clear Prints_ą",
    creatingPrint: "ł_Creating Print_ą",
    printError: "ł_Error, try again_ą"
});