define({
    title: "å_Map Title_ø",
    format: "å_Format_ø",
    layout: "å_Layout_ø",
    settings: "å_Advanced_ø",
    mapScaleExtent: "å_Map scale/extent_ø",
    preserve: "å_Preserve_ø",
    mapScale: "å_map scale_ø",
    mapExtent: "å_map extent_ø",
    forceScale: "å_Force scale_ø",
    getCurrentScale: "å_current_ø",
    mapMetadata: "å_Layout metadata_ø",
    author: "å_Author_ø",
    copyright: "å_Copyright_ø",
    fullLayoutOptions: "å_Full layout options_ø",
    scaleBarUnitsMetric: "å_Scale bar units metric_ø",
    scaleBarUnitsNonMetric: "å_Scale bar units non-metric_ø",
    unitsMiles: "å_Miles_ø",
    unitsKilometers: "å_Kilometers_ø",
    unitsMeters: "å_Meters_ø",
    unitsFeet: "å_Feet_ø",
    unitsYards: "å_Yards_ø",
    unitsNauticalMiles: "å_Nautical Miles_ø",
    lncludeLegend: "å_Include legend_ø",
    printQualityOptions: "å_Print quality_ø",
    dpi: "å_DPI_ø",
    mapOnlyOptions: "å_MAP_ONLY size_ø",
    width: "å_Width (px)_ø",
    height: "å_Height (px)_ø",
    print: "å_Print_ø",
    clearList: "å_Clear Prints_ø",
    creatingPrint: "å_Creating Print_ø",
    printError: "å_Error, try again_ø"
});