define({
    title: "Ă_Map Title_ș",
    format: "Ă_Format_ș",
    layout: "Ă_Layout_ș",
    settings: "Ă_Advanced_ș",
    mapScaleExtent: "Ă_Map scale/extent_ș",
    preserve: "Ă_Preserve_ș",
    mapScale: "Ă_map scale_ș",
    mapExtent: "Ă_map extent_ș",
    forceScale: "Ă_Force scale_ș",
    getCurrentScale: "Ă_current_ș",
    mapMetadata: "Ă_Layout metadata_ș",
    author: "Ă_Author_ș",
    copyright: "Ă_Copyright_ș",
    fullLayoutOptions: "Ă_Full layout options_ș",
    scaleBarUnitsMetric: "Ă_Scale bar units metric_ș",
    scaleBarUnitsNonMetric: "Ă_Scale bar units non-metric_ș",
    unitsMiles: "Ă_Miles_ș",
    unitsKilometers: "Ă_Kilometers_ș",
    unitsMeters: "Ă_Meters_ș",
    unitsFeet: "Ă_Feet_ș",
    unitsYards: "Ă_Yards_ș",
    unitsNauticalMiles: "Ă_Nautical Miles_ș",
    lncludeLegend: "Ă_Include legend_ș",
    printQualityOptions: "Ă_Print quality_ș",
    dpi: "Ă_DPI_ș",
    mapOnlyOptions: "Ă_MAP_ONLY size_ș",
    width: "Ă_Width (px)_ș",
    height: "Ă_Height (px)_ș",
    print: "Ă_Print_ș",
    clearList: "Ă_Clear Prints_ș",
    creatingPrint: "Ă_Creating Print_ș",
    printError: "Ă_Error, try again_ș"
});