define({
    title: "כן_Map Title_ש",
    format: "כן_Format_ש",
    layout: "כן_Layout_ש",
    settings: "כן_Advanced_ש",
    mapScaleExtent: "כן_Map scale/extent_ש",
    preserve: "כן_Preserve_ש",
    mapScale: "כן_map scale_ש",
    mapExtent: "כן_map extent_ש",
    forceScale: "כן_Force scale_ש",
    getCurrentScale: "כן_current_ש",
    mapMetadata: "כן_Layout metadata_ש",
    author: "כן_Author_ש",
    copyright: "כן_Copyright_ש",
    fullLayoutOptions: "כן_Full layout options_ש",
    scaleBarUnitsMetric: "כן_Scale bar units metric_ש",
    scaleBarUnitsNonMetric: "כן_Scale bar units non-metric_ש",
    unitsMiles: "כן_Miles_ש",
    unitsKilometers: "כן_Kilometers_ש",
    unitsMeters: "כן_Meters_ש",
    unitsFeet: "כן_Feet_ש",
    unitsYards: "כן_Yards_ש",
    unitsNauticalMiles: "כן_Nautical Miles_ש",
    lncludeLegend: "כן_Include legend_ש",
    printQualityOptions: "כן_Print quality_ש",
    dpi: "כן_DPI_ש",
    mapOnlyOptions: "כן_MAP_ONLY size_ש",
    width: "כן_Width (px)_ש",
    height: "כן_Height (px)_ש",
    print: "כן_Print_ש",
    clearList: "כן_Clear Prints_ש",
    creatingPrint: "כן_Creating Print_ש",
    printError: "כן_Error, try again_ש"
});