define({
    title: "須_Map Title_鷗",
    format: "須_Format_鷗",
    layout: "須_Layout_鷗",
    settings: "須_Advanced_鷗",
    mapScaleExtent: "須_Map scale/extent_鷗",
    preserve: "須_Preserve_鷗",
    mapScale: "須_map scale_鷗",
    mapExtent: "須_map extent_鷗",
    forceScale: "須_Force scale_鷗",
    getCurrentScale: "須_current_鷗",
    mapMetadata: "須_Layout metadata_鷗",
    author: "須_Author_鷗",
    copyright: "須_Copyright_鷗",
    fullLayoutOptions: "須_Full layout options_鷗",
    scaleBarUnitsMetric: "須_Scale bar units metric_鷗",
    scaleBarUnitsNonMetric: "須_Scale bar units non-metric_鷗",
    unitsMiles: "須_Miles_鷗",
    unitsKilometers: "須_Kilometers_鷗",
    unitsMeters: "須_Meters_鷗",
    unitsFeet: "須_Feet_鷗",
    unitsYards: "須_Yards_鷗",
    unitsNauticalMiles: "須_Nautical Miles_鷗",
    lncludeLegend: "須_Include legend_鷗",
    printQualityOptions: "須_Print quality_鷗",
    dpi: "須_DPI_鷗",
    mapOnlyOptions: "須_MAP_ONLY size_鷗",
    width: "須_Width (px)_鷗",
    height: "須_Height (px)_鷗",
    print: "須_Print_鷗",
    clearList: "須_Clear Prints_鷗",
    creatingPrint: "須_Creating Print_鷗",
    printError: "須_Error, try again_鷗"
});