define({
    title: "é_Map Title_È",
    format: "é_Format_È",
    layout: "é_Layout_È",
    settings: "é_Advanced_È",
    mapScaleExtent: "é_Map scale/extent_È",
    preserve: "é_Preserve_È",
    mapScale: "é_map scale_È",
    mapExtent: "é_map extent_È",
    forceScale: "é_Force scale_È",
    getCurrentScale: "é_current_È",
    mapMetadata: "é_Layout metadata_È",
    author: "é_Author_È",
    copyright: "é_Copyright_È",
    fullLayoutOptions: "é_Full layout options_È",
    scaleBarUnitsMetric: "é_Scale bar units metric_È",
    scaleBarUnitsNonMetric: "é_Scale bar units non-metric_È",
    unitsMiles: "é_Miles_È",
    unitsKilometers: "é_Kilometers_È",
    unitsMeters: "é_Meters_È",
    unitsFeet: "é_Feet_È",
    unitsYards: "é_Yards_È",
    unitsNauticalMiles: "é_Nautical Miles_È",
    lncludeLegend: "é_Include legend_È",
    printQualityOptions: "é_Print quality_È",
    dpi: "é_DPI_È",
    mapOnlyOptions: "é_MAP_ONLY size_È",
    width: "é_Width (px)_È",
    height: "é_Height (px)_È",
    print: "é_Print_È",
    clearList: "é_Clear Prints_È",
    creatingPrint: "é_Creating Print_È",
    printError: "é_Error, try again_È"
});