define({
    title: "Ж_Map Title_Я",
    format: "Ж_Format_Я",
    layout: "Ж_Layout_Я",
    settings: "Ж_Advanced_Я",
    mapScaleExtent: "Ж_Map scale/extent_Я",
    preserve: "Ж_Preserve_Я",
    mapScale: "Ж_map scale_Я",
    mapExtent: "Ж_map extent_Я",
    forceScale: "Ж_Force scale_Я",
    getCurrentScale: "Ж_current_Я",
    mapMetadata: "Ж_Layout metadata_Я",
    author: "Ж_Author_Я",
    copyright: "Ж_Copyright_Я",
    fullLayoutOptions: "Ж_Full layout options_Я",
    scaleBarUnitsMetric: "Ж_Scale bar units metric_Я",
    scaleBarUnitsNonMetric: "Ж_Scale bar units non-metric_Я",
    unitsMiles: "Ж_Miles_Я",
    unitsKilometers: "Ж_Kilometers_Я",
    unitsMeters: "Ж_Meters_Я",
    unitsFeet: "Ж_Feet_Я",
    unitsYards: "Ж_Yards_Я",
    unitsNauticalMiles: "Ж_Nautical Miles_Я",
    lncludeLegend: "Ж_Include legend_Я",
    printQualityOptions: "Ж_Print quality_Я",
    dpi: "Ж_DPI_Я",
    mapOnlyOptions: "Ж_MAP_ONLY size_Я",
    width: "Ж_Width (px)_Я",
    height: "Ж_Height (px)_Я",
    print: "Ж_Print_Я",
    clearList: "Ж_Clear Prints_Я",
    creatingPrint: "Ж_Creating Print_Я",
    printError: "Ж_Error, try again_Я"
});