define({
  root: {
    serviceURL: "Service URL",
    defaultTitle: "Default Title",
    defaultAuthor: "Default Author",
    defaultCopyright: "Default Copyright",
    defaultFormat: "Default Format",
    defaultLayout: "Default Layout",
    warning: "Incorrect input",
    ok: "OK"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});