define({
  root: {
    title: "Map Title",
    format: "Format",
    layout: "Layout",
    settings: "Advanced",
    mapScaleExtent: "Map scale/extent",
    preserve: "Preserve",
    mapScale: "map scale",
    mapExtent: "map extent",
    forceScale: "Force scale",
    getCurrentScale: "current",
    mapMetadata: "Layout metadata",
    author: "Author",
    copyright: "Copyright",
    fullLayoutOptions: "Full layout options",
    scaleBarUnitsMetric: "Scale bar units metric",
    scaleBarUnitsNonMetric: "Scale bar units non-metric",
    unitsMiles: "Miles",
    unitsKilometers: "Kilometers",
    unitsMeters: "Meters",
    unitsFeet: "Feet",
    unitsYards: "Yards",
    unitsNauticalMiles: "Nautical Miles",
    lncludeLegend: "Include legend",
    printQualityOptions: "Print quality",
    dpi: "DPI",
    mapOnlyOptions: "MAP_ONLY size",
    width: "Width (px)",
    height: "Height (px)",
    print: "Print",
    clearList: "Clear Prints",
    creatingPrint: "Creating Print",
    printError: "Error, try again"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": true
});