define({
    title: "æ_Map Title_Â",
    format: "æ_Format_Â",
    layout: "æ_Layout_Â",
    settings: "æ_Advanced_Â",
    mapScaleExtent: "æ_Map scale/extent_Â",
    preserve: "æ_Preserve_Â",
    mapScale: "æ_map scale_Â",
    mapExtent: "æ_map extent_Â",
    forceScale: "æ_Force scale_Â",
    getCurrentScale: "æ_current_Â",
    mapMetadata: "æ_Layout metadata_Â",
    author: "æ_Author_Â",
    copyright: "æ_Copyright_Â",
    fullLayoutOptions: "æ_Full layout options_Â",
    scaleBarUnitsMetric: "æ_Scale bar units metric_Â",
    scaleBarUnitsNonMetric: "æ_Scale bar units non-metric_Â",
    unitsMiles: "æ_Miles_Â",
    unitsKilometers: "æ_Kilometers_Â",
    unitsMeters: "æ_Meters_Â",
    unitsFeet: "æ_Feet_Â",
    unitsYards: "æ_Yards_Â",
    unitsNauticalMiles: "æ_Nautical Miles_Â",
    lncludeLegend: "æ_Include legend_Â",
    printQualityOptions: "æ_Print quality_Â",
    dpi: "æ_DPI_Â",
    mapOnlyOptions: "æ_MAP_ONLY size_Â",
    width: "æ_Width (px)_Â",
    height: "æ_Height (px)_Â",
    print: "æ_Print_Â",
    clearList: "æ_Clear Prints_Â",
    creatingPrint: "æ_Creating Print_Â",
    printError: "æ_Error, try again_Â"
});