define({
    title: "ก้_Map Title_ษฺ",
    format: "ก้_Format_ษฺ",
    layout: "ก้_Layout_ษฺ",
    settings: "ก้_Advanced_ษฺ",
    mapScaleExtent: "ก้_Map scale/extent_ษฺ",
    preserve: "ก้_Preserve_ษฺ",
    mapScale: "ก้_map scale_ษฺ",
    mapExtent: "ก้_map extent_ษฺ",
    forceScale: "ก้_Force scale_ษฺ",
    getCurrentScale: "ก้_current_ษฺ",
    mapMetadata: "ก้_Layout metadata_ษฺ",
    author: "ก้_Author_ษฺ",
    copyright: "ก้_Copyright_ษฺ",
    fullLayoutOptions: "ก้_Full layout options_ษฺ",
    scaleBarUnitsMetric: "ก้_Scale bar units metric_ษฺ",
    scaleBarUnitsNonMetric: "ก้_Scale bar units non-metric_ษฺ",
    unitsMiles: "ก้_Miles_ษฺ",
    unitsKilometers: "ก้_Kilometers_ษฺ",
    unitsMeters: "ก้_Meters_ษฺ",
    unitsFeet: "ก้_Feet_ษฺ",
    unitsYards: "ก้_Yards_ษฺ",
    unitsNauticalMiles: "ก้_Nautical Miles_ษฺ",
    lncludeLegend: "ก้_Include legend_ษฺ",
    printQualityOptions: "ก้_Print quality_ษฺ",
    dpi: "ก้_DPI_ษฺ",
    mapOnlyOptions: "ก้_MAP_ONLY size_ษฺ",
    width: "ก้_Width (px)_ษฺ",
    height: "ก้_Height (px)_ษฺ",
    print: "ก้_Print_ษฺ",
    clearList: "ก้_Clear Prints_ษฺ",
    creatingPrint: "ก้_Creating Print_ษฺ",
    printError: "ก้_Error, try again_ษฺ"
});