define({
    title: "Š_Map Title_ä",
    format: "Š_Format_ä",
    layout: "Š_Layout_ä",
    settings: "Š_Advanced_ä",
    mapScaleExtent: "Š_Map scale/extent_ä",
    preserve: "Š_Preserve_ä",
    mapScale: "Š_map scale_ä",
    mapExtent: "Š_map extent_ä",
    forceScale: "Š_Force scale_ä",
    getCurrentScale: "Š_current_ä",
    mapMetadata: "Š_Layout metadata_ä",
    author: "Š_Author_ä",
    copyright: "Š_Copyright_ä",
    fullLayoutOptions: "Š_Full layout options_ä",
    scaleBarUnitsMetric: "Š_Scale bar units metric_ä",
    scaleBarUnitsNonMetric: "Š_Scale bar units non-metric_ä",
    unitsMiles: "Š_Miles_ä",
    unitsKilometers: "Š_Kilometers_ä",
    unitsMeters: "Š_Meters_ä",
    unitsFeet: "Š_Feet_ä",
    unitsYards: "Š_Yards_ä",
    unitsNauticalMiles: "Š_Nautical Miles_ä",
    lncludeLegend: "Š_Include legend_ä",
    printQualityOptions: "Š_Print quality_ä",
    dpi: "Š_DPI_ä",
    mapOnlyOptions: "Š_MAP_ONLY size_ä",
    width: "Š_Width (px)_ä",
    height: "Š_Height (px)_ä",
    print: "Š_Print_ä",
    clearList: "Š_Clear Prints_ä",
    creatingPrint: "Š_Creating Print_ä",
    printError: "Š_Error, try again_ä"
});